### ISSUE TITLE
ShapeVector.setPolyScale does nothing

### ISSUE THREAD

**Issue by lilligreen** [GarageGames/Torque2D#107]
Not really sure what this method is supposed to scale. Values between 0 and 1 do nothing to the shape. I followed mPolygonScale to ShapeVector::generateLocalPoly, it is used to calculate the polygon half-size but then nothing is done with the half-size value. Scale is later set with mSize.

Don't know whether to classify this as a bug or just a method that is no longer needed and can be purged.

**Comment by greenfire27** [comment]
The function has been removed.
