### ISSUE TITLE
%worldPosition calculates different on Y Position for iOS than OSX effects onTouchDown, etc.

### ISSUE THREAD

**Issue by bigmonkgames** [GarageGames/Torque2D#118]
%worldPosition calculates different on Y Position for iOS than OSX effects onTouchDown, etc.

Noticed this when I deployed an app to my iPad. Seems as if I have to Touch about 20-25 units below the Object for it to trigger a Touch to the object. It's spot on correct when it runs on OSX. I have not investigated Source Code

In order for things to work correctly on my iPad I wrote this in my onTouchDown Function.

%x = getWord(%worldPosition,0);
%y = getWord(%worldPosition,1);

%newy = %y -25;
%newWorldPosition = %x SPC %newY;

%picked = mainScene.pickPoint(%newWorldPosition);

and the rest of the function as it would be.

Video showing Bug: http://youtu.be/yINDKZFqon4

**Comment by greenfire27** [comment]
Sounds like this was fixed with an iOS update.  Probably was a bug that had to do with the screen orientation lock.  I'll close this ticket.  Open a new ticket if you see the bug again.
