### ISSUE TITLE
setScreenMode() on OSX  issue

### ISSUE THREAD

**Issue by amjadyahya** [GarageGames/Torque2D#119]
When using setScreenMode(800, 600, 24, false) to switch from full screen to windowed mode the canvas turns white and it never switches to windowed mode and the application stops responding.

**Comment by greenfire27** [comment]
Hi amjadyahya,
This issue is over two years old now.  Is this still happening? If so what version of MacOS are you running?  Does it happen consistently?  

I'll give you a few days to answer and then I'll close the ticket.  Thanks!

**Comment by greenfire27** [comment]
Closing this ticket.  If a similar issue occurs please open a new ticket.  Thanks!
