### ISSUE TITLE
Password Field Crashes

### ISSUE THREAD

**Issue by Psp4804** [GarageGames/Torque2D#134]
Torque crashes when selecting censored password text.

Details @ http://www.garagegames.com/community/forums/viewthread/135770

**Comment by chaigler** [comment]
This doesn't happen on Windows. Can someone test this on other platforms?

**Comment by camporter** [comment]
This issue is OSX-specific. Opened a PR to fix the issue.

**Comment by greenfire27** [comment]
This has been corrected by removing OSX specific code to handle password characters.
