### ISSUE TITLE
ShapeVector doesn't draw polygons at all, just circles

### ISSUE THREAD

**Issue by Syrup84** [GarageGames/Torque2D#156]
**Branch:** Development
**Platforms:** iOS, Android, Emscripten
**Description:** ShapeVector doesn't draw polygons at all, just circles. 
**Reported:**
* http://www.garagegames.com/community/blogs/view/22563/3#comment-196012
* http://www.garagegames.com/community/blogs/view/22563/3#comment-196013

**Comment by greenfire27** [comment]
This should be corrected now in dev.  Can anybody confirm that it works on one of the affected platforms?

**Comment by greenfire27** [comment]
This has been corrected.
