### ISSUE TITLE
Class/Superclass Namespace bug

### ISSUE THREAD

**Issue by lilligreen** [GarageGames/Torque2D#181]
Reported here: http://www.garagegames.com/community/forums/viewthread/136922

Assigning an object a class first and then a superclass results in Namespace::unlinkClass error and the superclass is not assigned to the object. All other combinations (assign only a class, only a superclass, or superclass first then class) work fine.

So the workaround for now is if you need to use both fields, make sure to assign the object a superclass before the class.

**Comment by greenfire27** [comment]
Merged in Mike's fix for this.  Thanks Mike!
