### ISSUE TITLE
ERROR ON COMPILE: Missing DLL

### ISSUE THREAD

**Issue by Wargog** [GarageGames/Torque2D#212]
I have all the requirements installed and this has never come up compiling a program before, it says MSVCP100D.dll is missing, all VS C++ Redists are installed properly, so what here is the issue.
![error](https://cloud.githubusercontent.com/assets/5117696/3393594/e774756a-fcc8-11e3-926f-ffab82b33928.png)

**Comment by chaigler** [comment]
The correct way to fix this seems to be changing the VS projects to link against Leap.dll, rather than Leapd.dll (at least according to: https://developer.leapmotion.com/documentation/cpp/devguide/Project_Setup.html#windows-setting-up-a-c-project-in-visual-studio).

**Comment by greenfire27** [comment]
I no longer have this problem since the merge.  Good job!
