### ISSUE TITLE
Console crash when setting a field value on a non-existent object.

### ISSUE THREAD

**Issue by jamesu** [GarageGames/Torque2D#240]
For example with the following code placed at the end of main.cs....

	function functionCall()
	{
	   %localVar = 123;
	   return %localVar;
	}

	function doSomething()
	{
	   ImaginaryObject.foo = functionCall(); // <<< crash
	}

	doSomething();

A crash will occur due to the current variable not being cleared on exiting a function. This seems to be resolved in T3D, however the fix has not been incorporated into T2D.

**Comment by chaigler** [comment]
@jamesu I just tested this using the latest development version. Calling doSomething() did not cause a crash in either the release or debug builds. T2D didn't complain about ImaginaryObject not existing (which it probably should) but that's a minor issue. 

If you could re-test this on your end and let me know the results I would appreciate it. I'll leave this issue open for a few days, but unless someone else can verify the issue I'm going to recommend closing it.

**Comment by jamesu** [comment]
I'll have a look

**Comment by chaigler** [comment]
@jamesu Did you have a chance to take a look at this again? I made a few more attempts using various builds to get this to crash (on Windows only) but haven't had any issues.

**Comment by jamesu** [comment]
Cant directly reproduce here atm, possibly was fixed at some point or may require certain cases to trigger.

On a sidenote this somewhat related bug from https://github.com/GarageGames/Torque3D/issues/704 still affects T2D.

**Comment by chaigler** [comment]
Good catch. I'm going to close out this issue and open a new issue & pull request to fix the unexpected console behavior.
