### ISSUE TITLE
Git Hub need information

### ISSUE THREAD

**Issue by amritsql** [GarageGames/Torque2D#250]
I had a repository which i have deleted accidently, now can you please help me with the following queries.
1) Do you keep the backup of the repository which i maintained.
2) Is there any way you can let me know of how many clones or downloads were done for that repository which i maintained.

**Comment by MichPerry-GG** [comment]
That's entirely up to GitHub, not GarageGames, LLC or the Torque 2D committee. You'll have to contact GitHub's support for this.

**Comment by amritcbz** [comment]
@MichPerry-GG : thanks
