### ISSUE TITLE
emscripten build issue using 1.34.6

### ISSUE THREAD

**Issue by scottschafer** [GarageGames/Torque2D#253]
In order to get this to work, I had to change generate.sh and generate_release.sh from:
-DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN_PATH/cmake/Platform/Emscripten.cmake
to
-DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN_PATH/cmake/Modules/Platform/Emscripten.cmake

**Comment by greenfire27** [comment]
This is has been corrected per your suggestion.  The change is currently in the development branch.  Thanks for the heads up!
