### ISSUE TITLE
Windows 8 / 10 support

### ISSUE THREAD

**Issue by yurembo** [GarageGames/Torque2D#271]
Torque 2D is great!
It supports iOS and Android mobile technologies.
Unfortunately, cause, it's renderer is build upon OpenGL, Torque 2D doesn't support Windows Phone 7, 8 and obviously 10. WP 7 is old, but 8 and 10 is important.
What should we do to add support of these mobile operating systems?
I think we should make a new renderer with DirectX 11 / 12, should we?

**Comment by greenfire27** [comment]
I would happily merge any pull request that get's us onto WP 8 and 10, but for now I suggest we focus on working out the bugs that we have with iOS and Android.  Once those work well again we can set our eyes on additional platforms.

**Comment by mattiascibien** [comment]
Acutally you can do OpenGL on Windows 8 / 10 thanks to the [angle](https://github.com/MSOpenTech/angle)

**Comment by yurembo** [comment]
Wow, this is really great!
I will try!

**Comment by fiammybe** [comment]
Given the state of mobile platforms (OpenGL being replaced with Vulkan, and Windows Mobile almost disappeared and no longer maintained by MS), this could be closed I think.

**Comment by greenfire27** [comment]
I can agree with that. Plus there doesn't seem to be much interest in building a new renderer based on directX.
