### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by yurembo** [GarageGames/Torque2D#272]
Eclipse is old.
Nowadays Android developers use Android Studio to create Android applications.
By the way, Torque 2D doesn't include support to Android Studio, but Eclipse only.
This summer Casey Doran added support to Android Studio (https://www.garagegames.com/community/forums/viewthread/142325/) in his fork of Torque 2D (https://github.com/elementc/Torque2D/tree/android-studio).
I have tested this cod, it works very fine!
I think you should add this cod to original repository.

**Comment by greenfire27** [comment]
I'm on board with this.  If you're using his support for Android Studio are you able to create a pull request with the needed files?  I would gladly merge such a request.

**Comment by yurembo** [comment]
Ok, I'll make this
