### ISSUE TITLE
Unexpected script behavior

### ISSUE THREAD

**Issue by kynora** [GarageGames/Torque2D#276]
The function in different file not work untill I declare inside the same script file  of calling function.
Example below if I move ReceiveNetGameRoom to other file, it display message "Enable to find method ReceiveNetGameRoom". In platform windows work fine but android is not working.

function ClientCmdSetGhostObject(%ghostId)
{   
   %object = $Connection.resolveGhostID(%ghostId);
   %className = %object.getClassName();
   if (%className $= "NetGameRoom")
       ReceiveNetGameRoom(%object);
   else if (%className $= "NetBoardGameAccount")
       ReceiveAccountGhost(%object);
}

function ReceiveNetGameRoom(%object)
{
   GameRoomGhost.add(%object);
   %object.internalName = %object.id;
   UpdateRoomList();
   if (%object.player1Id $= $YourID)
      Canvas.popDialog(BusyDlg);
}

**Comment by chaigler** [comment]
Where are the ClientCmdSetGhostObject and ReceiveNetGameRoom functions declared? Are you getting any script compilation errors in the console? 

@yurembo Have you seen anything like this before?

**Comment by kynora** [comment]
I use remote command SetGhostObject from server. I am sure that all script compiled and running ok in Windows platform. But it is not working in Android. It can not find method ReceiveNetGameRoom, this method delcare in one file that I include in module and also get .dso file from Windows too.

I am not sure it relate to android executte source bug? Because I use hack code in android to let it execute dso directly.

// make it compile dso directly from those plateform
#if defined(TORQUE_OS_ANDROID)
	compiled = false;

	const char *filenameOnly = dStrrchr(scriptFileName, '/');
	if(filenameOnly)
	++filenameOnly; //remove the / at the front
	else
	filenameOnly = scriptFileName;

	char pathAndFilename[1024];
	Platform::makeFullPathName(filenameOnly, pathAndFilename, sizeof(pathAndFilename), dsoPath);

	dStrcpyl(nameBuffer, sizeof(nameBuffer), pathAndFilename, ".dso", NULL);

	compiledStream = ResourceManager->openStream(nameBuffer);
	if(compiledStream)
	{
		compiledStream->read(&version);
	}
	else
	{
		// We have to exit out here, as otherwise we get double error reports.
		delete [] script;
		execDepth--;
		return false;
	}
#endif

**Comment by chaigler** [comment]
Is it actually compiling the script files? Does exec() fail to find the file(s)?

**Comment by kynora** [comment]
It not complile in android, cause of file write permission. I just get dso from windows.
But I think this bug is block by File I/O bug. I will reproduce again after file IO is fixed. At the moment I just get hacking code to prevent this bug for my game.
And it is very weird bug, when I move script file to new module, it work fine.

I wait this bug fix and test, I can not say now. (File i/o broken on Android #242)

**Comment by kynora** [comment]
This bug should be relate to resolveGhostID not work well.
I try to simulate 1000 ghosts from server to client. Some client ghost object not recieve correctly.

function ClientCmdSetGhostObject(%ghostId)
{
   %object = $Connection.resolveGhostID(%ghostId);
   %className = %object.getClassName();
}

Only about 300 object receive with no error. and other with out put :
Unable to find object: '0' attempting to call function 'getClassName'

Now I investigate deeply on this.

**Comment by kynora** [comment]
I can not reproduce this bug. I close this bug.
