### ISSUE TITLE
OSX Won't Build Since Ogg Support was Added

### ISSUE THREAD

**Issue by greenfire27** [GarageGames/Torque2D#286]
Since adding ogg support, OSX won't build.  We need to get ogg supporting working with OSX.

**Comment by camporter** [comment]
Found some time to look into this, I have a fix on #295

**Comment by greenfire27** [comment]
Merged in your fix.  Can anyone confirm that we can now build again on OSX?  Also that oggs play?  Thanks!

**Comment by camporter** [comment]
Builds work on OSX and run fine. I forgot to test ogg specifically but I
will tomorrow with the existing audio toy.

**Comment by camporter** [comment]
Checked ogg support, audio assets seem to work fine under OSX.

**Comment by greenfire27** [comment]
Great!  Thanks again!
