### ISSUE TITLE
Add build information for OSX to guide

### ISSUE THREAD

**Issue by camporter** [GarageGames/Torque2D#296]
Not sure what the easiest way to edit the wiki is, but with the libogg and libvorbis dependencies, there is a need to install the libraries on OSX now. With the updates in #295 this should be as simple as running:

```
brew install libogg libvorbis --universal
```

to get the libraries included by Xcode properly. Obviously the change to the wiki might want to coincide with another release of Torque2D since that issue doesn't exist on the last release.

**Comment by greenfire27** [comment]
You seem like the right guy to write such an update.  Update the wiki in your fork and add a link to the updated page in a comment here.  When we push everything to master I'll take your changes and make them part of the main wiki and close the issue.  Thanks for all your help!

**Comment by greenfire27** [comment]
This was added to chapter 2 of the Getting Started Guide.
