### ISSUE TITLE
Android Studio compile failed

### ISSUE THREAD

**Issue by yurembo** [GarageGames/Torque2D#311]
I'm wonder. Why is newest version from development branch in Android studio compile failed?

**Comment by greenfire27** [comment]
We're getting ready to announce 3.2 today, so if you could figure it out I would be grateful. :)

**Comment by dottools** [comment]
This should be fixed in PR #312. Enjoy!

**Comment by yurembo** [comment]
Thanks. I can not wait to try this :+1:

**Comment by greenfire27** [comment]
Resolved.

**Comment by yurembo** [comment]
Oh, great! I have tested this already, and everything work realy fine!
Only, I decreased SDK version from 22 to 19:
 compileSdkVersion 19
minSdkVersion 19
targetSdkVersion 19
And it works great
