### ISSUE TITLE
OSX build and precompileds broken- libogg error

### ISSUE THREAD

**Issue by elementc** [GarageGames/Torque2D#320]
Since the 3.2 release, I can't get the engine to build on OSX. When compiling, it complains about needing libogg.dylib come link time, and when running a precompiled build, it crashes looking for libogg.dylib. I don't know the OSX build system well enough to fix it (yet, I'm tinkering with it now), but It sounds like we're not shipping the OSX version of certain OGG (and possibly vorbis) libs. Is this a boneheaded error on my part or do we have an issue here?

**Comment by greenfire27** [comment]
Unfortunately you now have to install the Vorbis libraries to get it to compile on MacOX.  For lack of a better place, we documented it in chapter 2 of the getting started guide.  You can find it [here](https://github.com/GarageGames/Torque2D/wiki/Getting-Started-Guide#chapter-2-compiling-the-engine).

I'm open to a better way to do this if you have any ideas.

**Comment by elementc** [comment]
Are we not able to include mac libs for libogg and libvorbis in
engine/lib/? I thought that was the point of that entire dir. Is there a
technical or licensing reason why not?

On Tue, Jan 26, 2016 at 2:20 PM, Peter Robinson <notifications@github.com>
wrote:

> Unfortunately you now have to install the Vorbis libraries to get it to
> compile on MacOX. For lack of a better place, we documented it in chapter 2
> of the getting started guide. You can find it here
> <https://github.com/GarageGames/Torque2D/wiki/Getting-Started-Guide#chapter-2-compiling-the-engine>
> .
>
> I'm open to a better way to do this if you have any ideas.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GarageGames/Torque2D/issues/320#issuecomment-175187406>
> .
>



-- 
Casey Doran <http://my.fit.edu/~cdoran2011>

**Comment by elementc** [comment]
I'd hardly call this Solution found since the precompiled builds are still broken...

**Comment by greenfire27** [comment]
There's no technical or licensing reason. The real problem is that we only have two steering committee members and we're both Windows guys.  That leaves the rest of the platforms on life support - waiting for some heroic programmer to come along, take responsibility for them and join the steering committee.  Until that day we'll have to hobble along on pull requests from the community.

If you add the mac libs to the engine/lib directory and statically link to them, I would gladly merge your pull request.

**Comment by dottools** [comment]
Well I wouldn't add pre-compiled libs to the repository, but instead I think what he's asking is to build and then link against the already provided libogg and libvorbis library sources just like how Torque 3D does it. I'll see if I can get someone to help us take a look and hopefully resolve the Mac OS X side of things regarding those two libraries.

**Comment by greenfire27** [comment]
I appreciate that, thanks!  I'm just sorry I can't do more to fix the problem myself.

**Comment by lwiskowski** [comment]
I'm trying to use your precompiled builds on OSX and its complaining about libogg.dylib @elementc is correct, you need to distribute these libraries.

**Comment by greenfire27** [comment]
We're working on it.  Definitely a problem we want to solve!

**Comment by greenfire27** [comment]
Hi guys! I just uploaded the XCode project file which should correct this problem.  Can one of you guys grab latest from development and confirm that this is corrected?  Thanks!
