### ISSUE TITLE
List the todos publicly to finish them quickly

### ISSUE THREAD

**Issue by mebjas** [GarageGames/Torque2D#321]
We should have Torque2D on Todofy, I tried it on my fork and there are about 169 todos in the master branch. Here's the link: https://todofy.org/r/fybot/Torque2D

This will give clear visibility on what all need to be finished, and platform has various feature to assist the process.

**Comment by greenfire27** [comment]
That neat!  I'll look into it.  Keep in mind though that some of those todos might be a decade old and might no longer be relevant.  That's a pretty big list to weed through.

**Comment by dottools** [comment]
Although it is a neat project, but it's yet another website we would have to maintain and keep track of as a community which is the usual downside to those things. Just like [uservoice.com](https://garagegames.uservoice.com/forums/194449-torque-2d-mit) and [trello.com](https://trello.com/torque2dmit) were neat ideas at first, but became cumbersome chore. These days we just depend on following the github project issue tracker for any issues or tasks that need to be resolved/completed.

Another thing all, but 10, TODOs/FIXMEs are from third party libraries and as a matter of policy we only update from upstream, don't modify those libraries.

**Comment by mebjas** [comment]
@greenfire27 - you think a todo is old and not relevant, hide it. View it from hidden section if you want:
<img width="1193" alt="screen shot 2016-01-27 at 9 11 02 pm" src="https://cloud.githubusercontent.com/assets/3007365/12618583/80f7497a-c53a-11e5-8981-e53f893c729a.png">

@dottools - TODOs from third party libraries showing up, go to repo settings and ignore directories. Again we have a section to view them if need be.
<img width="1193" alt="screen shot 2016-01-27 at 9 12 43 pm" src="https://cloud.githubusercontent.com/assets/3007365/12618633/badef8e0-c53a-11e5-9998-8f41a723e4bf.png">

Now about a service becoming a liability, you don't need to do anything extra here. It's simple flow:
**You want to add a todo** just add a todo in your code along with other stuffs and push it.
```c
// TODO: implement this using cookies
```
Todofy will track and add it to public list.

**You want to finish a todo in a week**
```c
// TODO: implement this using cookies @deadline 1 week
```
Todofy got you covered, it will notify you in time. You can add a `@reminder` in similar fashion

**You think greenfire27 is the guy for this task** - put it in the code Todofy will tell him
```c
// TODO: implement this using cookies @assign greenfire27
```
Todofy will notify **greenfire27**

Similarly you can use add `labels`, `tag` other users, or set `priority` for the todo in the code itself.

**Comment by dottools** [comment]
It is inappropriate to assign deadlines and assignments in source code comments. The git commit pollution would be insane. That's why the issue tracker exists in the first place, of which we are doing right now discussing this instead of posting commits to the code repository with code comments talking about this very topic for instance.

**Comment by mebjas** [comment]
The feature is to enhance the workflow! Current flow would be:
 - you push the code
 - create an issue
 - may be assign a user to it
 - discuss it.
 - resolve it with another push

With Todofy, your flow will be 
 - Push the code with a todo comment

> It will auto track the todo, if directive is present auto assign, notify respective users, and even auto create a Github issue if the directive for that is present.

 - Resolve the issue with another push

The problem with standard issue tracker is **an issue need to be added manually**.

And about the code pollutions, todos are not permanent members of the code, they are supposed to be added and remove ASAP.


P.S: You can do all these (assignments, labels, deadline, priority) right from the dashboard without making code changes.

**Comment by greenfire27** [comment]
So what we have here is a neat project that allows you to do all your project management directly from the source code.  We're going to pass, but thanks anyway.  We're a community of volunteers.  Nobody assigns tasks to anyone, there's no deadlines, and nobody finishes todos.  People who create issues don't have code to check in first and if somebody adds a new feature it needs to be completely done before we merge it.  Todofy is probably perfect some teams but it doesn't work for us.
