### ISSUE TITLE
ActionMap Modifier Break command ignored

### ISSUE THREAD

**Issue by capnlove** [GarageGames/Torque2D#341]
An Example illustrates this better than explanation.

**Example**
1- An ActionMap binding exists for the keyboard key "w".
2- At runtime, the user presses "Shift" and "w".
3 - The code finds no ActionMap bindings for "shift w" and looks for a binding without the supplied modifier. i.e. the code looks if there is a binding for "w", disregarding the modifier "shift"
4 - The binding for "w" is found and its MAKE command is executed.

Problem : Its BREAK command in the smBreakTable is never populated, thus releasing the "w" key while holding "shift" does not call the appropriate binding.

**Comment by greenfire27** [comment]
Fixed in #343.  Thanks Simon!  In my years working with the engine there's a number of cases where key up events never occurred, but I never took the time to hunt down the problem.  Similar issues have surfaced from other people and they just might be resolved with this as well.
