### ISSUE TITLE
Shift vs. lshift & rshift

### ISSUE THREAD

**Issue by capnlove** [GarageGames/Torque2D#344]
In the **createEventDescriptor** method of **ActionMap**, when binding an Action to a key with a modifier (i.e. "shift w") only "shift", "ctrl", "alt", "cmd" or "opt" may be used.

When a modifier key is bound by itself, "lshift" or "rshift" can be used, "latl" and "ralt" and "lcontrol" and "rcontrol" can be specified, specifying the right or left ctrl/alt/shift keys on keyboards.

Option A - The documentation should reflect that binding modifier + keys only accepts general-purpose bindings
Option B - Change createEventDescriptor to accept left and right variations of each key.

**Comment by greenfire27** [comment]
I prefer option 2.  I'm getting the impression that nobody has looked at this in a long time.  Thanks for logging these issues.

**Comment by capnlove** [comment]
Already taken care of in #343

**Comment by greenfire27** [comment]
I remember seeing this a decade ago when I made my first game with the engine and couldn't use the left and right variations with other keys.  Thanks for fixing this!
