### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by yurembo** [GarageGames/Torque2D#346]
on OS X a compilation processes fine but linking is error,
older engine versions were build well,
do you know what is the problem?

**Comment by greenfire27** [comment]
What's the linking error?  We added a number of files in the last release.  The new project file should include these but it's possible that you might need to add them for some reason.

**Comment by yurembo** [comment]
Here's a error:
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I searched an info: somebody says that there are dublicates of included files

**Comment by greenfire27** [comment]
Did you hand merge your project file? You probably don't have a needed file included.  The 3.3 updated added new files for the audio stuff and the font stuff.  Look at #338 to see what files were added and removed from the Xcode project file and then make sure your project file includes the same files.

**Comment by yurembo** [comment]
I have downloaded last development-branch engine

**Comment by yurembo** [comment]
My project file is equivalent to this file and other files are taken place.
Does anybody try to compile Torque 2D from OS X?

**Comment by yurembo** [comment]
for iOS build is well,
but for OS X build is failed

**Comment by yurembo** [comment]
Already you've got the solution: [here](https://github.com/GarageGames/Torque2D/wiki/Getting-Started-Guide#chapter-2-compiling-the-engine)

**Comment by greenfire27** [comment]
Right, that slipped my mind. I should have pointed you there.  Glad you found the solution!
