### ISSUE TITLE
TextSprite unspecified Size hangs application

### ISSUE THREAD

**Issue by capnlove** [GarageGames/Torque2D#349]
When creating a text sprite where the Size field of the TextSprite object is unspecified or smaller than one rendered character (That is just my guess), the application hangs, endlessly looping on a black screen.

Happens regardless of chosen font, tried it with the ones supplied and 2 custome ones.

Tested with the latest develoment branch on Windows

**Comment by greenfire27** [comment]
Probably gets stuck in an endless loop trying to place that first character.  Good catch!  I'll get it corrected soon.

**Comment by greenfire27** [comment]
Fixed it!
