### ISSUE TITLE
Project Manager for OS X

### ISSUE THREAD

**Issue by yurembo** [GarageGames/Torque2D#351]
Hello everybody!
I converted my Project Manager for OS X.
You know: I developed a Project Manager for Windows using .NET.
Then I recompiled this with Mono.
And now you can launch a Project Manager from OS X.
To begin, you should install Mono framework.
After that you can launch *.exe files with Mono framework from a terminal like this:
`mono ProjectManager.exe`
Notice, you can run *.exe files that were build with MonoDevelop/Xamarin Studio.
You can download a full source code of a Project Manager for OS X from my GitHub page: [Project Manager for OS X](https://github.com/yurembo/ProjectManager-OS-X)

**Comment by capnlove** [comment]
And why is this an issue? Shouldn't it be a Pull request or a different repo?

**Comment by yurembo** [comment]
@capnlove you see this is a link to my page
