### ISSUE TITLE
The Magic of Torque: The Art of game development with Torque 2D engine

### ISSUE THREAD

**Issue by yurembo** [GarageGames/Torque2D#354]
Hello friends!

I wrote a book in Russian about a game development with Torque 2D.

You will read about a history of a game development industry. By the way, the largest part of this book is devoted to development of computer and mobile games. The development of 4 games of different genres examines during a book. Since the central theme of the book is a cross-platform engine Torque 2D, therefore games are built with it, moreover, you'll see a porting games to different platforms and their placement on e-marketplace.

You can download CD content from [author’s web-site (rus)](http://www.t2d-dev.ru.)

The book is published by Solon-Press.
Publisher started a pre-order of the book. You can make the pre-order on the [publisher's web-site](https://clck.ru/9vitX.)

**Comment by greenfire27** [comment]
That's pretty awesome!  If I spoke Russian I would definitely buy a copy.

**Comment by yurembo** [comment]
Thank you Peter!

**Comment by elementc** [comment]
Awesome! Why is this an issue?

**Comment by fiammybe** [comment]
I propose to close this :-)

**Comment by greenfire27** [comment]
Well, we did let it ride for two years. I hope the book did well Yurembo.
