### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by kynora** [GarageGames/Torque2D#356]
iOS 9 required IPv6 support in app to connect to the network.

**Comment by dottools** [comment]
I'll look into implementing IPv6 into both Torque game engines. Hopefully somebody else with a Mac and iOS experience can test and debug the code on iOS 9 and Mac OS X (10.11.x) to make sure it does work when I get the code ready sometime this upcoming week. The only problem for me would be testing out Apple's Berkley socket API extensions to doing IPv6 address synthesize from IPv4 literal addresses.

**Comment by Juason** [comment]
I'll do what I can to help test on the iOS side.

**Comment by kynora** [comment]
@dottools , do you progress with your implement? I can help you if need.

**Comment by kynora** [comment]
I start to implement for all platform now. If no problem I will make pull request.

**Comment by kynora** [comment]
I have been merge the code from T3D and testing only IPv4, (I dont have IPv6 environment). The test work fine with platforms : Windows, Android, iOS, Linux.
I close this bug and open the pull request #394 .
