### ISSUE TITLE
How to build a server?

### ISSUE THREAD

**Issue by yurembo** [GarageGames/Torque2D#363]
Torque 3D gives everything you need to build multiplayer games.
How to build a multiplayer game with Torque 2D?

**Comment by kynora** [comment]
I have been build multiplayer with Torque2D, you can learn from wiki : Checker Tutorial.
https://github.com/GarageGames/Torque2D/wiki/Network-Tutorial
I think garagegame should rewrite document from offline TGEA document, because this document is very good to know about the engine for beginner.

**Comment by yurembo** [comment]
@kynora 
Thank you!
