### ISSUE TITLE
Cannot compile the code in Ubuntu 16.04 - AudioDescription::AudioDescription()

### ISSUE THREAD

**Issue by Arash1234** [GarageGames/Torque2D#400]
Hi, 

I cannot "make" the code in my Ubuntu 16.04. The following error is raised:

`/home/arash/torque2d/Torque2D/engine/compilers/Make/../../source/2d/sceneobject/SceneObject_ScriptBinding.h:4503: undefined reference to `AudioDescription::AudioDescription()'
collect2: error: ld returned 1 exit status`

[Full Output](http://paste.opensuse.org/2948873)

This happens both in release and debug versions

**Comment by capnlove** [comment]
Seems to be linked with my integration of AudioDescriptions, thinking it's only a matter of solution/project/makefile that weren't updated on Linux.

**Comment by greenfire27** [comment]
I've been considering putting together an automatic build for a while to avoid these problems.  I've been looking at Travis CI.  Seem straight forward enough but I have no experience with it.  Maybe I'll take the plunge this weekend and try setting something up.  There's too many platforms and we're stretched too thin to adequately test every pull request.

**Comment by kynora** [comment]
To fix this issue :
In file engine\compilers\Make\Torque2D
Add include source :
	../../source/audio/audioDescriptions.cc \

**Comment by greenfire27** [comment]
Using Kynora's fix above, this should be correct now in v3.4 of the engine.
