### ISSUE TITLE
Compiling Dev branch on Android

### ISSUE THREAD

**Issue by Mpskydog** [GarageGames/Torque2D#404]
Has anyone been able to compile an Android .apk with the recent version of the Development branch? I spent some time, will probably spend some more but haven't been able to resolve some of the errors I'm getting in android studio. I'm happy to share the specific problems, but wanted to know if there is a change in the build process that maybe hasn't been updated?

I was still following the [Android Development Guide](https://github.com/GarageGames/Torque2D/wiki/Android-Development-Guide)

**Comment by greenfire27** [comment]
I don't believe anyone is on top of keeping the Android stuff up to date.  The development guide is also pretty dated.  As I understand, Eclipse is not used very much anymore.

If you get it running, I would gladly merge a pull request with your changes.

**Comment by dottools** [comment]
@Mpskydog Did you try these instructions, that were linked at the bottom of the Android Development Guide, for Android Studio? http://forums.torque3d.org/viewtopic.php?f=31&t=612&p=5102#p5094

I haven't retested the instructions with latest T2D and Android Studio releases, so might be incorrect though.

**Comment by greenfire27** [comment]
Specifically we've added files with some of the checkins in dev and they were probably never added the android project files.  I would hope including them would fix all the errors.  I would hope...

**Comment by Mpskydog** [comment]
@dottools I did indeed follow those directions. I will review everything and try again sometime this week, and let you know what I encounter.

**Comment by dottools** [comment]
I have fixed all Android build issues for Development branch in PR #405. Enjoy! :)

**Comment by greenfire27** [comment]
@Mpskydog Let me know if everything is working now and I'll close the issue. Thanks!

**Comment by Mpskydog** [comment]
I just had a chance to try running this again, and the build/push worked on the first try. Amazing, thanks for taking the time for this Nathan and Peter.

**Comment by dottools** [comment]
You're welcome. 👍
