### ISSUE TITLE
Black screen on Win 10 1903

### ISSUE THREAD

**Issue by cweissha** [GarageGames/Torque2D#427]
This is only an issue in Win 10 patch 1903. Everything was fine on 1809.

The executable starts up and my screen goes black. Exec is still running normally but display doesn't return to normal till reboot. No errors in console. Happens in full-screen or windowed mode. Happens with a fresh download on 2.0 or 3.4. Works fine if I have two monitors set to "extend desktop", only seems to fail on a single monitor setup.

I've reproduced this error on 4 different machines, 2 laptops w/ old nvidia cards, one desktop w/ onboard video, one desktop with nvidia 1070.

**Comment by greenfire27** [comment]
I've known about this for sometime, but only because people who play my game (Pirate Code) keep complaining about it.  The thing is, I haven't been able to reproduce it - but I have two monitors! So this might be missing information I've been looking for.  Thanks for posting!

**Comment by greenfire27** [comment]
Also, apparently I was still on 1809... I look forward to reproducing this bug soon. Again, can't thank you enough.

**Comment by cweissha** [comment]
You are welcome. Glad I could help. I'm hoping that someone already has a solution, but I'll start working on this issue later next week too.

To add a tiny bit more info: Once the screen has gone black you can sometimes get back by bringing up the task manager or plugging in a second monitor. On my main computer the only way to get the screen back is to plug in a second monitor and then change resolution on the main display. I have since tested on one more hardware configuration and there the problem was more intermittent, sometime the game would run, sometime I'd get a black screen and sometimes I'd get this strange tearing/streaking effect that I've never seen before. Hard to describe, but large blocks of diagonal white lines that would move down the screen at a speed proportional to FPS.

**Comment by greenfire27** [comment]
I narrowed it down the the gamma correction. I commented out the offending rows and committed directly to the master branch (not normal procedure, but desperate times...). Anyway, get latest and let me know if all is well again.

**Comment by cweissha** [comment]
Works for me. Thank you very much!
