### ISSUE TITLE
canvas.setCursor( ) is not working

### ISSUE THREAD

**Issue by amjadyahya** [GarageGames/Torque2D#78]
When you try to change the cursor image using canvas.setCursor() nothing happens and the default cursor stays the same.

new GuiCursor(newCursor)  
{  
        hotSpot = "1 1";  
        renderOffset = "0 0";  
        bitmapName = "./assets/images/newCursor.png";  
}; 
canvas.setCursor(newCursor);

This issue is confirmed only on Windows.

**Comment by greenfire27** [comment]
Fixed at last.
