### ISSUE TITLE
TAML "WriteDefaults" field fatal error

### ISSUE THREAD

**Issue by amjadyahya** [GarageGames/Torque2D#79]
%taml.WriteDefaults=true;  

generates a fatal error: fatal error simObject.cc @ 935 -> field value cannot be NULL.

setWriteDefaults() also generates the same error.

However ..

%taml.WriteDefaults=false;  

does not generate any errors.

I'm on Windows XP, using T2D development.

**Comment by greenfire27** [comment]
This was corrected using a change very close to lukaspj's solution.  It also passes the test that mike explained in pull request #227.

Problem solved.
